services:
  mysql:
    image: mysql:8.4
    container_name: inventario_mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: Battery..1Chekelete961204
      MYSQL_DATABASE: inventario
      MYSQL_USER: Luis
      MYSQL_PASSWORD: Battery..1

    ports:
      - "3307:3306"

    volumes:
      - inventario_mysql_data:/var/lib/mysql

volumes:
  inventario_mysql_data:
